// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8nzaVzPoAofFUm6FFXBHeKMac3chMeHk',
    appId: '1:869441481795:android:405b4ca359ead7c25bb8f6',
    messagingSenderId: '869441481795',
    projectId: 'mybio-neel19',
    storageBucket: 'mybio-neel19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATKGBHW-7ywRITVH_CU2ATM6yvMHDXvb4',
    appId: '1:869441481795:ios:31d64e6fcd0f192f5bb8f6',
    messagingSenderId: '869441481795',
    projectId: 'mybio-neel19',
    storageBucket: 'mybio-neel19.firebasestorage.app',
    androidClientId: '869441481795-sh8ic0u4tm0q9h93mirec8h36okuqc9c.apps.googleusercontent.com',
    iosClientId: '869441481795-ledradrughkn3vo87n863t0j1bcoigau.apps.googleusercontent.com',
    iosBundleId: 'com.folyo.neelbio',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDirvLXRbT0xo5oSLPPeTTJ61UPOmeE2p8',
    appId: '1:869441481795:web:5756e4b11aef5e085bb8f6',
    messagingSenderId: '869441481795',
    projectId: 'mybio-neel19',
    authDomain: 'mybio-neel19.firebaseapp.com',
    storageBucket: 'mybio-neel19.firebasestorage.app',
    measurementId: 'G-HQDMKS848J',
  );

}